from __future__ import annotations

import csv
from datetime import date
from decimal import Decimal
from pathlib import Path

import pytest
from app.anomaly import detect_anomalies
from app.etl import clean_merchant
from app.services.import_service import make_dedupe_key


def test_synthetic_anomaly_precision_recall_and_false_alert_rate():
    root = Path(__file__).parents[2]
    labels_path = root / "data" / "sample_statement.labels.csv"
    if not labels_path.exists():
        pytest.skip("synthetic labels are generated by CI before tests")
    rows = list(csv.DictReader(labels_path.open()))
    transactions: list[dict[str, object]] = []
    seen: set[str] = set()
    for row in rows:
        merchant = clean_merchant(row["description"])
        key = make_dedupe_key(
            date.fromisoformat(row["date"]), merchant, Decimal(row["amount"])
        )
        if key in seen or row["recurring"] == "1":
            continue
        seen.add(key)
        transactions.append(
            {
                "key": key,
                "amount": float(row["amount"]),
                "category": row["category"],
                "merchant": merchant,
            }
        )

    flags = detect_anomalies(
        [float(row["amount"]) for row in transactions],
        [str(row["category"]) for row in transactions],
        [str(row["merchant"]) for row in transactions],
    )
    predicted = {str(transactions[flag.index]["key"]) for flag in flags}
    truth = {
        row["dedupe_key"]
        for row in csv.DictReader((root / "backend/tests/fixtures/anomaly_truth.csv").open())
        if row["expected_anomaly"] == "1"
    }
    true_positive = len(predicted & truth)
    false_positive = len(predicted - truth)
    precision = true_positive / len(predicted)
    recall = true_positive / len(truth)
    false_alerts_per_100 = false_positive / len(transactions) * 100
    assert precision >= 0.70
    assert recall >= 0.70
    assert false_alerts_per_100 <= 1.0
