from __future__ import annotations

from pathlib import Path

import pytest
from fastapi.testclient import TestClient


def _sample_csv() -> bytes:
    path = Path(__file__).parents[2] / "data" / "sample_statement.csv"
    if not path.exists():
        pytest.skip("synthetic statement is generated by CI before tests")
    return path.read_bytes()


def test_alerts_include_injected_anomalies_and_exclude_recurring_charges(client: TestClient):
    imported = client.post(
        "/api/imports",
        files={"file": ("sample_statement.csv", _sample_csv(), "text/csv")},
    )
    assert imported.status_code == 201

    response = client.get("/api/alerts", params={"from": "2026-01-01"})
    assert response.status_code == 200
    alerts = response.json()["alerts"]
    merchants = {alert["description_raw"] for alert in alerts}
    assert "BIG APPLIANCE WAREHOUSE" in merchants
    assert "OVERSEAS ATM WITHDRAWAL" in merchants
    assert not any("GREENFIELD APARTMENTS" == merchant for merchant in merchants)
    assert not any("STATE FARM INSURANCE" == merchant for merchant in merchants)
    assert all(alert["signals"] for alert in alerts)


def test_alerts_reject_invalid_date(client: TestClient):
    response = client.get("/api/alerts", params={"from": "not-a-date"})
    assert response.status_code == 422
